### PR TITLE
Frontend Init + Dockerizes MongoDB/Frontend/Backend

### PR DESCRIPTION
**Pull request by EricLi-Dev**
Initial frontend next.js code

Get services up:
```docker-compose up --build -d```

Links:
[Frontend](http://localhost:3000)
[Backend](http://localhost:8080/api/home)
[MongoDB](http://localhost:27017)
[MongoExpress](http://localhost:8081)

### CODE REVIEW

**Comment by jubuyer** [comment]
Closes https://github.com/csci-499-sp24/FaceStylizer/issues/18 (navbar added),
Closes https://github.com/csci-499-sp24/FaceStylizer/issues/19 (image section added),
Closes https://github.com/csci-499-sp24/FaceStylizer/issues/20 (arrow below hero text added),
Closes https://github.com/csci-499-sp24/FaceStylizer/issues/21 (upload section added)
Closes #25 (frontend dockerized)

**Review by henryfan03 — DISMISSED** [review]
lgtm

**Review by Dulinag — APPROVED** [review]
good

**Review by henryfan03 — APPROVED** [review]
lgtm

**Pull request merged**
