### PR TITLE
Integrating Google Authentication to React App

### PR DESCRIPTION
**Pull request by George-Sucuzhanay**
Added Google Authentication Library to enable Google Sign In and direct users to a redirected link

Testing Instructions:

1. run both client and server with npm run dev
2. click on the sign in button
3. click on sign in with google with your google account
4. you should be redirected to http://localhost:3000/home and the following message should be displayed:
"You are signed in successfully with Google Auth!"

### CODE REVIEW

**Comment by George-Sucuzhanay** [comment]
Will be modifying PR to changes made in PR #36 to integrate a sign in form with Google Auth upon approval of #36

**Review by jubuyer — DISMISSED** [review]
```js
  const googleLogin = useGoogleLogin({
    onSuccess: (tokenResponse) => {
      console.log('Google login successful', tokenResponse);
      router.push('/home'); // Change final page to homepage -> /
      // You can now use the tokenResponse to authenticate the user in your app
    },
    onError: () => {
      console.error('Google login failed');
      // Handle login errors here
    },
    flow: 'auth-code', // Use 'auth-code' for the authorization code flow
  });
```
Can these two changes be implemented:
- On success, the user is given a message through a pop up that they've successfully logged in with google
  - This can also be done through a JS alert box, but a pop up would look nicer
- Modify the ` router.push('/home');` so that the user remains in the homepage

**Review by Dulinag — APPROVED** [review]
lgtm

**Review by jubuyer — APPROVED** [review]
Looks good for merging.

**Pull request merged**
